\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename hello.info
@include version.texi
@settitle Hello @value{VERSION}

@defcodeindex op
@syncodeindex op cp
@c %**end of header

@copying
This manual is for Hello (version @value{VERSION}, @value{UPDATED}),
a simple program that prints greetings.

Copyright (C) GCK

Permission is granted to copy, distribute and/or modify this document
under the terms of the BSD 3-Clause License.
<https://opensource.org/license/bsd-3-clause>
@end copying

@dircategory Basics
@direntry
* Hello: (hello).               Print greetings.
@end direntry

@titlepage
@title Hello
@subtitle for version @value{VERSION}, @value{UPDATED}
@author GCK
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Hello

This manual is for Hello (version @value{VERSION}, @value{UPDATED}),
a simple program that prints greetings.
@end ifnottex

@menu
* Overview::		General information.
* Sample output::	Examples.
* Invoking hello::	How to run @command{hello}.
* Reporting bugs::	Sending bug reports.
* Concept index::	Index of concepts.
@end menu


@node Overview
@chapter Overview

@cindex greetings
The @command{hello} program prints a default message:

@example
Hello, World!
@end example

If given arguments, it prints greetings for each:

@example
Hello, Alice!
Hello, Bob!
@end example

It is implemented in C and licensed under the BSD 3-Clause license.


@node Sample output
@chapter Sample output

Running @samp{hello} without arguments:

@example
$ hello
Hello, World!
@end example

Running @samp{hello Alice Bob}:

@example
$ hello Alice Bob
Hello, Alice!
Hello, Bob!
@end example


@node Invoking hello
@chapter Invoking @command{hello}

@cindex invoking
@cindex usage
The general form is:

@example
hello [@var{OPTION}] [@var{NAME}...]
@end example

With no arguments, prints @samp{Hello, World!}.  
With one or more names, prints a greeting for each.

@command{hello} also accepts standard options via
@code{parse_standard_options}, such as:

@table @option
@item --help
@opindex --help
Display usage information.

@item --version
@opindex --version
Display version and license information.
@end table


@node Reporting bugs
@chapter Reporting bugs

Please report bugs or suggestions to the maintainer of this program.
Include:

@itemize @bullet
@item The version of Hello (@samp{hello --version}).
@item The system and compiler used.
@item The exact command line and output.
@end itemize


@node Concept index
@unnumbered Concept index

@printindex cp

@bye
